### ISSUE TITLE
[修复] 用户回复n无法获取文章

### ISSUE THREAD

**Issue by xtremforce** [midoks/wp-weixin-robot#1]
查了一看应该是 function wordpress_cmd 里面的 bug

源码中：
case 'n':$result = $this->wp->news($suffix);
当用户仅回复「n」不带数字时，会出现错误 
(看debug似乎是调取了11篇文章，不知为何)

反正这三行，改回你上面写的 $int 就ok了
case 'n':$result = $this->wp->news($int);
case 'h':$result = $this->wp->hot($int);
case 'r':$result = $this->wp->rand($int);

**Comment by midoks** [comment]
谢谢,提醒了,好久没有更新了。还有人用哦。

**Comment by xtremforce** [comment]
> 谢谢,提醒了,好久没有更新了。还有人用哦。

当然有啦！简洁实用，希望不要放弃哦，我的站就在用。 https://www.iplaysoft.com
